-file("/usr/local/lib/erlang/lib/parsetools-2.0.11/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(puppy_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./puppy_scan.xrl", 59).

-export([reserved_word/1]).

%% reserved_word(Atom) -> Bool
%%   return 'true' if Atom is an Erlang reserved word, else 'false'.

reserved_word('after') -> true;
reserved_word('begin') -> true;
reserved_word('case') -> true;
reserved_word('try') -> true;
reserved_word('cond') -> true;
reserved_word('catch') -> true;
reserved_word('andalso') -> true;
reserved_word('orelse') -> true;
reserved_word('end') -> true;
reserved_word('fun') -> true;
reserved_word('if') -> true;
reserved_word('let') -> true;
reserved_word('of') -> true;
reserved_word('query') -> true;
reserved_word('receive') -> true;
reserved_word('when') -> true;
reserved_word('bnot') -> true;
reserved_word('not') -> true;
reserved_word('div') -> true;
reserved_word('rem') -> true;
reserved_word('band') -> true;
reserved_word('and') -> true;
reserved_word('bor') -> true;
reserved_word('bxor') -> true;
reserved_word('bsl') -> true;
reserved_word('bsr') -> true;
reserved_word('or') -> true;
reserved_word('xor') -> true;
reserved_word('spec') -> true;
reserved_word(_) -> false.

base(L, Cs) ->
    H = string:chr(Cs, $#),
    case list_to_integer(string:substr(Cs, 1, H-1)) of
  B when B > 16 -> {error,"illegal base"};
  B ->
      case base(string:substr(Cs, H+1), B, 0) of
    error -> {error,"illegal based number"};
    N -> {token,{integer,L,N}}
      end
    end.

base([C|Cs], Base, SoFar) when C >= $0, C =< $9, C < Base + $0 ->
    Next = SoFar * Base + (C - $0),
    base(Cs, Base, Next);
base([C|Cs], Base, SoFar) when C >= $a, C =< $f, C < Base + $a - 10 ->
    Next = SoFar * Base + (C - $a + 10),
    base(Cs, Base, Next);
base([C|Cs], Base, SoFar) when C >= $A, C =< $F, C < Base + $A - 10 ->
    Next = SoFar * Base + (C - $A + 10),
    base(Cs, Base, Next);
base([_|_], _, _) -> error;     %Unknown character
base([], _, N) -> N.

cc_convert([$$,$\\|Cs]) ->
    hd(string_escape(Cs));
cc_convert([$$,C]) -> C.

string_gen([$\\|Cs]) ->
    string_escape(Cs);
string_gen([C|Cs]) ->
    [C|string_gen(Cs)];
string_gen([]) -> [].

string_escape([O1,O2,O3|S]) when
  O1 >= $0, O1 =< $7, O2 >= $0, O2 =< $7, O3 >= $0, O3 =< $7 ->
    [(O1*8 + O2)*8 + O3 - 73*$0|string_gen(S)];
string_escape([$^,C|Cs]) ->
    [C band 31|string_gen(Cs)];
string_escape([C|Cs]) when C >= $\000, C =< $\s ->
    string_gen(Cs);
string_escape([C|Cs]) ->
    [escape_char(C)|string_gen(Cs)].

escape_char($n) -> $\n;       %\n = LF
escape_char($r) -> $\r;       %\r = CR
escape_char($t) -> $\t;       %\t = TAB
escape_char($v) -> $\v;       %\v = VT
escape_char($b) -> $\b;       %\b = BS
escape_char($f) -> $\f;       %\f = FF
escape_char($e) -> $\e;       %\e = ESC
escape_char($s) -> $\s;       %\s = SPC
escape_char($d) -> $\d;       %\d = DEL
escape_char(C) -> C.

-file("/usr/local/lib/erlang/lib/parsetools-2.0.11/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./puppy_scan.erl", 366).
yystate() -> 55.

yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,58};
yystate(57, [37|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(57, [10|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(57, Ics, Line, Tlen+1, 26, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(57, Ics, Line, Tlen+1, 26, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,57};
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line+1, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 42 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [61|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 24, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [124|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 24, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(49, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line+1, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, 0, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,48};
yystate(47, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(46, [37|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 24, Tlen);
yystate(46, [10|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line+1, Tlen+1, 24, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 24, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(38, Ics, Line, Tlen+1, 24, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(44, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [64|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(43, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(43, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,43};
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, 25, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(42, Ics, Line, Tlen+1, 25, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,42};
yystate(41, [92|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, [34|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, [10|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line+1, Tlen+1, 6, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(49, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(49, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(49, Ics, Line, Tlen+1, 6, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,41};
yystate(40, [101|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, [69|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,40};
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(39, [64|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(37, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line+1, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [62|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 24, Tlen);
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,35};
yystate(34, [62|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 24, Tlen);
yystate(34, [45|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 24, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,34};
yystate(33, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line+1, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,33};
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(32, [35|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 2, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, 2, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(30, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(29, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(28, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(27, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(26, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(23, [61|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 24, Tlen);
yystate(23, [60|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(23, [58|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 24, Tlen);
yystate(23, [47|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 24, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,23};
yystate(22, [43|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 24, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,22};
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(25, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,21};
yystate(20, [58|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 24, Tlen);
yystate(20, [45|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 24, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(18, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(15, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(14, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line+1, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [94|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 56, C =< 93 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 95 ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(11, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line+1, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(7, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(6, [92|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [39|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [10|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,6};
yystate(5, [37|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(5, [10|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 38 ->
    yystate(5, Ics, Line, Tlen+1, 26, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,5};
yystate(4, [61|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 24, Tlen);
yystate(4, [60|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 24, Tlen);
yystate(4, [45|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 24, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,4};
yystate(3, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(1, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line+1, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLen, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLen, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, _) ->
    yyaction_26();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("./puppy_scan.xrl", 14).
yyaction_0(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_1/2}).
-file("./puppy_scan.xrl", 15).
yyaction_1(TokenChars, TokenLine) ->
     base (TokenLine, TokenChars) .

-compile({inline,yyaction_2/2}).
-file("./puppy_scan.xrl", 16).
yyaction_2(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("./puppy_scan.xrl", 17).
yyaction_3(TokenChars, TokenLine) ->
     Atom = list_to_atom (TokenChars),
     { token, case reserved_word (Atom) of
     true -> { Atom, TokenLine } ;
     false -> { atom, TokenLine, Atom }
     end } .

-compile({inline,yyaction_4/3}).
-file("./puppy_scan.xrl", 24).
yyaction_4(TokenChars, TokenLen, TokenLine) ->
     S = lists : sublist (TokenChars, 2, TokenLen - 2),
     case catch list_to_atom (string_gen (S)) of
     { 'EXIT', _ } -> { error, "illegal atom " ++ TokenChars } ;
     Atom -> { token, { atom, TokenLine, Atom } }
     end .

-compile({inline,yyaction_5/2}).
-file("./puppy_scan.xrl", 29).
yyaction_5(TokenChars, TokenLine) ->
     { token, { var, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_6/3}).
-file("./puppy_scan.xrl", 32).
yyaction_6(TokenChars, TokenLen, TokenLine) ->
     S = lists : sublist (TokenChars, 2, TokenLen - 2),
     { token, { string, TokenLine, string_gen (S) } } .

-compile({inline,yyaction_7/2}).
-file("./puppy_scan.xrl", 35).
yyaction_7(TokenChars, TokenLine) ->
     { token, { char, TokenLine, cc_convert (TokenChars) } } .

-compile({inline,yyaction_8/1}).
-file("./puppy_scan.xrl", 36).
yyaction_8(TokenLine) ->
     { token, { '->', TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("./puppy_scan.xrl", 37).
yyaction_9(TokenLine) ->
     { token, { ':-', TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("./puppy_scan.xrl", 38).
yyaction_10(TokenLine) ->
     { token, { '||', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("./puppy_scan.xrl", 39).
yyaction_11(TokenLine) ->
     { token, { '<-', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("./puppy_scan.xrl", 40).
yyaction_12(TokenLine) ->
     { token, { '++', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("./puppy_scan.xrl", 41).
yyaction_13(TokenLine) ->
     { token, { '--', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("./puppy_scan.xrl", 42).
yyaction_14(TokenLine) ->
     { token, { '=/=', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("./puppy_scan.xrl", 43).
yyaction_15(TokenLine) ->
     { token, { '==', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("./puppy_scan.xrl", 44).
yyaction_16(TokenLine) ->
     { token, { '=:=', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("./puppy_scan.xrl", 45).
yyaction_17(TokenLine) ->
     { token, { '/=', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("./puppy_scan.xrl", 46).
yyaction_18(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("./puppy_scan.xrl", 47).
yyaction_19(TokenLine) ->
     { token, { '=<', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("./puppy_scan.xrl", 48).
yyaction_20(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("./puppy_scan.xrl", 49).
yyaction_21(TokenLine) ->
     { token, { '<<', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("./puppy_scan.xrl", 50).
yyaction_22(TokenLine) ->
     { token, { '>>', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("./puppy_scan.xrl", 51).
yyaction_23(TokenLine) ->
     { token, { '::', TokenLine } } .

-compile({inline,yyaction_24/2}).
-file("./puppy_scan.xrl", 53).
yyaction_24(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("./puppy_scan.xrl", 54).
yyaction_25(TokenLine) ->
     { end_token, { dot, TokenLine } } .

-compile({inline,yyaction_26/0}).
-file("./puppy_scan.xrl", 55).
yyaction_26() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.11/include/leexinc.hrl", 282).
